### PR TITLE
Removed Compass dependency from Sass file

### PR DESCRIPTION
**Pull request by theonicolaou**
When I tried to use the Sass version of the plugin, I wasn't aware that I had to install Compass. I didn't really want to, as I don't use it in any of my other projects. So I removed all the Compass dependencies in the Sass file.

I look forward to your feedback!

Theo

### CODE REVIEW

**Comment by kball** [comment]
Hi @theonicolaou thank you for the PR!

Broadly, this looks good, the one request I have prior to merging is to re-instate the README, with the SCSS build as an option, rather than the total rewrite of the README.  Thanks!

**Comment by theonicolaou** [comment]
Hi @kball,

Thanks for your feedback! I have amended the README as requested and also cleaned up the comments in the Gruntfile a little.

Please let me know if there is anything else you would like me to do!

Thanks

Theo

**Comment by bcole808** [comment]
+1 for this! I would love to see this merged as we have the same situation where we would like to use the SASS file but not install Compass.

**Comment by theonicolaou** [comment]
Hi @kball, do you have an ETA on when this PR will get merged? (or is there anything else you would like me to do for it to be approved?)

Thanks

Theo

**Comment by kball** [comment]
@theonicolaou sorry I got pulled off on other projects and forgot about this. Will test it out and hopefully merge today

**Pull request merged**
