### PR TITLE
Move slider on mouse hover

### PR DESCRIPTION
**Pull request by daohoangson**
Reimplement 7e2208e: add a move_slide_on_hover event that moves the slider handler during hover event, disabled by default.

### CODE REVIEW

**Comment by raphaeleidus** [comment]
if this is turned on for a touch device what will happen?
should we force this feature off for users using touch devices

**Comment by daohoangson** [comment]
My bad, it looks like it doesn't work smoothly on touch browser. I will update the PR to disable itself when appropriate.

**Comment by raphaeleidus** [comment]
@daohoangson https://github.com/zurb/twentytwenty/pull/85 was just merged and it touches a lot of the same code that you were working on. I suggest you look it over and figure out how this can work with it. If you need some help, let me know

**Comment by daohoangson** [comment]
I haven't had time to update this PR for touch device yet. Will do in a few
days, thank you for the heads up.

**Comment by daohoangson** [comment]
@raphaeleidus I have merged #85 into this and they work beautifully together. The best way to use this now is probably with `move_slider_on_hover = true` and `move_with_handle_only = false`. Great UX on both desktop and mobile.

**Pull request merged**
