### PR TITLE
Refactor of the 1.0 release, adds in AngularJS support, removes runtime dependencies, etc.

### PR DESCRIPTION
**Pull request by mhayes**
Hey guys - this PR adds in a bunch of changes to the TwentyTwenty plugin. Most notably:
- Adds in support for AngularJS, so there is now a jQuery and AngularJS version
  - All common functionality has been moved into `src/js/core.js` to prevent too much redundant code in the different plugin versions
- Removes dependencies on external touch libraries (i.e. ngTouch for AngularJS or jquery.event.move for jQuery)
- Uses [webpack](https://webpack.github.io) for the build system resulting in a single JS file, there is no need to include a CSS in your project

I see this as the starting ground for a 2.0 release of the plugin. Would love to hear thoughts of other things that can be part of this release.

### CODE REVIEW

**Comment by rafibomb** [comment]
Awesome! Great work! We used Twenty Twenty recently in the [Foundation for Emails blog post](http://zurb.com/article/1424/call-me-e-schmail-conquering-the-beast-th)

I'll ask the engineers who are more knowledgeable than I to check it out!

**Comment by raphaeleidus** [comment]
hey @mhayes this is no longer mergeable.
When you first opened the PR you moved some files around, introducing a `src` folder, unfortunately you didn't use `git mv` so the diff shows as you deleting the entire file and the adding a new one, this destroys the history for the files so I wont be able to merge this even with it touched up to resolve conflicts. If you are still interested in what v2 could be let me know I think you have some great ideas here.

**Comment by mhayes** [comment]
Hey @raphaeleidus thanks for following up with me. I've actually switched over to using VueJS for most of my work these days (also ported TwentyTwenty to VueJS here: https://github.com/mhayes/vue-twentytwenty) so not looking to make any updates on this.

Cheers!

**Comment by raphaeleidus** [comment]
coo. that makes sense. I am definitely going to review this and pull some items from it. Thank you for the great work

**Pull request closed without merging**
